[package]
name = "bar_daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log_to_linear = {path = "../.log_to_linear"}
thiserror = "1.0.33"
tokio = { version = "1.20.1", features = ["full"] }
